import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

// generated by shadcn
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// created by chatgpt
export function isBase64Image(imageData: string) {
  const base64Regex = /^data:image\/(png|jpe?g|gif|webp);base64,/;
  return base64Regex.test(imageData);
}

// created by chatgpt
export function formatDateString(dateString: string) {
  const options: Intl.DateTimeFormatOptions = {
    year: "numeric",
    month: "short",
    day: "numeric",
  };

  const date = new Date(dateString);
  const formattedDate = date.toLocaleDateString(undefined, options);

  const time = date.toLocaleTimeString([], {
    hour: "numeric",
    minute: "2-digit",
  });

  return `${time} - ${formattedDate}`;
}

// created by chatgpt
export function formatThreadCount(count: number): string {
  if (count === 0) {
    return "No Threads";
  } else {
    const threadCount = count.toString().padStart(2, "0");
    const threadWord = count === 1 ? "Thread" : "Threads";
    return `${threadCount} ${threadWord}`;
  }
}

export const catchAsync = async (promise: Function) => {
  return async () => {
    try {
      await promise();
    } catch (e) {
      throw e;
    }
  };
};

export const camelToSnakeCase = (str: string) => {
  return str.split(" ").join("_").toLowerCase();
};

export const showLikesCount = (likesCount: number) => {
  if (likesCount <= 0) {
    return "";
  }

  if (likesCount === 1) {
    return `${likesCount} like`;
  }

  return `${likesCount} likes`;
};

export const getImgUrl = (imageUrl: string, imgWidth: number) => {
  if (!imageUrl.includes('res.cloudinary.com')){
    return imageUrl
  }

  return `${imageUrl}?w=${imgWidth}`;
};
